### ISSUE TITLE
好像只能下一页，-p 5 也不行。

### ISSUE THREAD

**Issue by roger-xavier1** [ArjixGamer/A-collection-of-sauce-scrapers-that-I-made#1]

**Comment by ArjixWasTaken** [comment]
ah yes, chinese

**Comment by ArjixWasTaken** [comment]
"-p 5" is for getting the first 5 pages

Google translate:
> “ -p 5”用于获取前5页

**Comment by ArjixWasTaken** [comment]
-p is short for --pages
as you can see [here](https://github.com/ArjixGamer/A-collection-of-sauce-scrapers-that-I-made/blob/main/sankaku.py#L51)
